<?xml version="1.0" encoding="utf-8"?><Database Name="CubeAfricaDemo" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=GOLDIE-PC;Initial Catalog=CubeAfricaDemo;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CubeAfricaDemoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tUsers" Member="tUsers">
    <Type Name="tUser">
      <Column Name="pkUserId" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sFirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="sLastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="sCompany" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="sEmailAddress" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="sCellNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="sWorkNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="sPassword" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>